version: '4' 
services:
  node-app:
    container_name: node-app
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    environment:
      - port=4000
      - DB_HOST=12345
    env_file:
      - ./.env
      
